backend = "glx";

#TRANSPARENCIA GLOBAL
inactive-opacity = 0.95;
inactive-opacity-override = false;

#TRANSPARECIA ESPECIFICA
opacity-rule = [
  "65:class_g = 'kitty'",
  "75:class_g = 'Code'",
  "85:class_g = 'Spotify'",
  "85:Name = 'audiorelay'",
   ];


