backend = "glx";

#TRANSPARENCIA GLOBAL
inactive-opacity = 0.97;
inactive-opacity-override = false;

#TRANSPARECIA ESPECIFICA
opacity-rule = [
  "65:class_g = 'kitty'",
  "85:class_g = 'VSCodium'",
  "85:class_g = 'Spotify'",
  "85:class_g = 'com-azefsw-audioconnect-desktop-app-MainKt'",

   ];


